refact: improve code formatting and consistency in multiple scripts

diff --git a/common/.local/bin/git-fetch-pr b/common/.local/bin/git-fetch-pr
--- a/common/.local/bin/git-fetch-pr
+++ b/common/.local/bin/git-fetch-pr
@@ -2,17 +2,17 @@
 # usage: git fetch-pr PULL-REQUEST-ID
 
 if [ "$#" -ne 1 ]; then
-    echo "usage: git fetch-pr PULL-REQUEST-ID" >&2
-    exit 1
+  echo "usage: git fetch-pr PULL-REQUEST-ID" >&2
+  exit 1
 fi
 
 ID="$1"
 
 case "$ID" in
-  ''|*[!0-9]*)
-    echo "invalid pull-request-id $1" >&2
-    exit 1
-    ;;
+'' | *[!0-9]*)
+  echo "invalid pull-request-id $1" >&2
+  exit 1
+  ;;
 esac
 
 BRANCH_NAME="pr$ID"
